### PR TITLE
Restructure

### PR DESCRIPTION
**Pull request by martin-martin**
Restructure project and improve styling.

### CODE REVIEW

**Comment by mingyyy** [comment]
review? are you working more on this? I don't mind work on it a little bit.
One more thing to do....

**Comment by martin-martin** [comment]
Yes! :) It's a fun project! I cleaned it up a little, but there's lots more work to do.

Just felt it was a good point to make a PR and merge it back - if you agree of course!

Also thought it could be a fun way to continue learning this whole github stuff, right? ;)
So pull down my branch and check it out, and gimme a review if you think it's good to go!

**Comment by mingyyy** [comment]
yes, sir! I am not very productive in Singapore at all!
barely made any commit since I arrived. :)
got a lot of free food though.

**Comment by LuckyLub** [comment]
Free food is almost just as good as commiting Ming.

**Comment by LuckyLub** [comment]
Wait, did I accept all the changes? or just of the commit I was looking at?

**Comment by LuckyLub** [comment]
It's pretty hard to actually review it. 

I fetched your branch, but I'm missing some functionalities, no? 
How do we answer questions or alter our profile? 

I love the picture of the person who asked the question btw. Caught me by suprise there mr martin. :+1:

**Comment by martin-martin** [comment]
Hei - yeah the project is not finished! This is just a branch doing some basic restructuring and style improvements.

So there's a couple of other things we could still implement! Was just breathing some life into this, not doing it all ;)

**Comment by martin-martin** [comment]
@mingyyy - when (and if) you approve as well you can go ahead and merge the PR!

**Comment by martin-martin** [comment]
@

> How do we answer questions or alter our profile?

I think there could definitely be some functionality to **alter the profiles**.

I don't think we were planning to be able to answer questions - the original idea was to use it as an on-site ticketing app. My suggestion is to keep it like that, really similar to the numbers you take when you go stand in line for the butcher e.g. in the Netherlands. So essentially just to record that a question was asked, and which one, and then be able to mark it as answered if one of the students or an instructor (or the person who asked the question) managed to figure it out.

I like the feature of having the name + image of the person who asked and answered it associated with the question so that students could seek out the person who henceforth holds the secrets to the universe and subsequently can allow them to ascend to a higher phase of being themselves.

There's lots to do, though, a couple of tasks are marked with `TODO` in the code. You could go ahead and create issue from those!

**Comment by LuckyLub** [comment]
Cool, **I'm in**!
I'll be doing it in my spare time, so don't expect daily updates. However, I think I have some time left tonight.

**Comment by LuckyLub** [comment]
Oke, I made some issues, but I don't really know how we should continue. Should we first merge this (@mingyyy don't forget to accept the request!) before we split it up? Or shouldn't we split it up at all and just claim issues, so that we can make small pull requests? It would make it simpler to review maybe.

**Comment by martin-martin** [comment]
Awesome! :) Yes,  that'd be the way to move forward:

1) Merge the PR so this is our new master
2) pick an issue,  create a new feature branch
3) work on that branch until you solved the issue, then make a PR

And anyone is welcome to pick (or make) an issue and continue on this,  if you want :) 
@melissa @daniel @blake @sadie

**Comment by LuckyLub** [comment]
Oke cool! So let's merge this baby.
btw: I think you tagged the wrong melissa, daniel and blake :wink:

**Comment by spacerest** [comment]
wrong me, too

**Comment by martin-martin** [comment]
Lol, I did it from my phone and there were no autocomplete suggestions... 😅 Sorry everyone!

**Comment by martin-martin** [comment]
Ok, I'll be merging this now. @mingyyy is probably too busy socializing at home ;)
🎉 has begun.

**Pull request merged**
